#include "globals.h"


#ifndef UNITTEST

#include "move.h"

uint32_t _GLOBAL_MOVE_KP = MOVE_KP;
uint32_t _GLOBAL_MOVE_KI = MOVE_KI;
uint32_t _GLOBAL_MOVE_KD = MOVE_KD;
uint32_t _GLOBAL_MOVE_DEFAULT_SPEED_STRAIGHT_MM_S = MOVE_DEFAULT_SPEED_STRAIGHT_MM_S;
uint32_t _GLOBAL_MOVE_DEFAULT_SPEED_TURN_MM_S = MOVE_DEFAULT_SPEED_TURN_MM_S;
bool _GLOBAL_MOVE_SURFACE_LOW_GRIP = false;

#else

uint32_t _GLOBAL_MOVE_KP = 0;
uint32_t _GLOBAL_MOVE_KI = 0;
uint32_t _GLOBAL_MOVE_KD = 0;
uint32_t _GLOBAL_MOVE_DEFAULT_SPEED_STRAIGHT_MM_S = 0;
uint32_t _GLOBAL_MOVE_DEFAULT_SPEED_TURN_MM_S = 0;
bool _GLOBAL_MOVE_SURFACE_LOW_GRIP = false;

#endif
